import { useState } from "react";

import "../styles/notifications.css";

import useDeviceStatus from "../hooks/useDeviceStatus";


export default function Notifications() {

  const { device } =
    useDeviceStatus();


  /*
   * Temporary local settings.
   *
   * These will later be saved
   * to Firestore per user.
   */
  const [settings, setSettings] =
    useState({

      emailNotifications: false,

      pushNotifications: false,

      temperatureAlerts: true,

      humidityAlerts: true,

      systemAlerts: true,

      completionAlerts: true,

    });


  /* =========================================
     TOGGLE SETTING

     Currently local only.

     Firestore user preferences will be
     connected later.
  ========================================= */

  const toggleSetting =
    (key) => {

      setSettings((current) => ({

        ...current,

        [key]:
          !current[key],

      }));

    };


  /* =========================================
     DEVICE STATUS MESSAGE
  ========================================= */

  const getDeviceMessage = () => {

    /*
     * ESP32 has never created
     * its Firestore document.
     */
    if (!device.exists) {

      return {

        title:
          "Waiting for SmartChip device",

        message:
          "No SmartChip ESP32 device has connected yet. Alerts will become available when the device comes online.",

        status:
          "waiting",

      };

    }


    /*
     * Device document exists but
     * heartbeat is no longer active.
     */
    if (!device.online) {

      return {

        title:
          "SmartChip device is offline",

        message:
          "The device is currently not sending live updates. No new alerts can be received until the ESP32 comes back online.",

        status:
          "offline",

      };

    }


    /*
     * Device is online.
     *
     * Real alerts will later come
     * from Firestore.
     */
    return {

      title:
        "No active alerts",

      message:
        "SmartChip is online and no active system alerts have been detected.",

      status:
        "online",

    };

  };


  const deviceMessage =
    getDeviceMessage();


  return (

    <div className="page-container notifications">


      {/* ================= HEADER ================= */}

      <div className="notifications-header">

        <h1>
          Notifications & Alerts
        </h1>


        <p className="muted">

          Monitor SmartChip system alerts
          and notification preferences

        </p>

      </div>



      {/* ================= DEVICE STATUS ================= */}

      <div
        className={`card notification-device-status ${

          deviceMessage.status

        }`}
      >

        <div className="notification-status-header">

          <div>

            <h3>

              {device.online
                ? "● Device Online"
                : device.exists
                ? "● Device Offline"
                : "● Waiting for Device"}

            </h3>


            <p className="muted">

              Device ID:
              {" "}
              {device.deviceId}

            </p>

          </div>


          <span
            className={`notification-status-badge ${

              deviceMessage.status

            }`}
          >

            {device.online
              ? "ONLINE"
              : device.exists
              ? "OFFLINE"
              : "WAITING"}

          </span>

        </div>

      </div>



      {/* ================= MAIN GRID ================= */}

      <div className="grid two notifications-grid">


        {/* ================= ALERT PANEL ================= */}

        <div className="card alerts-panel">


          <div className="alerts-header">

            <div>

              <h3>
                Recent Alerts
              </h3>


              <p className="muted">

                Real alerts will appear here
                when generated by SmartChip.

              </p>

            </div>


            <span className="alert-count">

              0 Alerts

            </span>

          </div>



          {/* ================= EMPTY STATE ================= */}

          <div className="no-alerts">

            <div className="no-alerts-icon">

              {device.online
                ? "✓"
                : "⚠"}

            </div>


            <h3>

              {deviceMessage.title}

            </h3>


            <p>

              {deviceMessage.message}

            </p>


            <div className="alerts-info">

              <strong>
                Alert System Status
              </strong>


              <span>

                {device.online
                  ? "Waiting for alert monitoring"
                  : "Waiting for device connection"}

              </span>

            </div>

          </div>


        </div>



        {/* ================= SETTINGS PANEL ================= */}

        <div className="card settings-panel">


          <h3>
            ⚙ Notification Settings
          </h3>


          <p className="muted">

            Configure which SmartChip events
            should generate notifications.

          </p>


          {/* ================= CONNECTION NOTICE ================= */}

          <div className="notification-settings-notice">

            <strong>
              Settings are currently local.
            </strong>


            <span>

              Notification preferences will
              be saved to your account in
              Firestore in a later phase.

            </span>

          </div>



          {/* ================= NOTIFICATION CHANNELS ================= */}

          <SettingsGroup
            title="Notification Channels"
          >

            <Toggle

              label="Email Notifications"

              checked={
                settings.emailNotifications
              }

              onChange={() =>
                toggleSetting(
                  "emailNotifications"
                )
              }

            />


            <Toggle

              label="Push Notifications"

              checked={
                settings.pushNotifications
              }

              onChange={() =>
                toggleSetting(
                  "pushNotifications"
                )
              }

            />

          </SettingsGroup>



          {/* ================= SENSOR ALERTS ================= */}

          <SettingsGroup
            title="Sensor Alerts"
          >

            <Toggle

              label="Temperature Alerts"

              checked={
                settings.temperatureAlerts
              }

              onChange={() =>
                toggleSetting(
                  "temperatureAlerts"
                )
              }

            />


            <Toggle

              label="Humidity Alerts"

              checked={
                settings.humidityAlerts
              }

              onChange={() =>
                toggleSetting(
                  "humidityAlerts"
                )
              }

            />

          </SettingsGroup>



          {/* ================= SYSTEM EVENTS ================= */}

          <SettingsGroup
            title="System Events"
          >

            <Toggle

              label="System Alerts"

              checked={
                settings.systemAlerts
              }

              onChange={() =>
                toggleSetting(
                  "systemAlerts"
                )
              }

            />


            <Toggle

              label="Drying Completion Alerts"

              checked={
                settings.completionAlerts
              }

              onChange={() =>
                toggleSetting(
                  "completionAlerts"
                )
              }

            />

          </SettingsGroup>


        </div>


      </div>



      {/* ================= FUTURE ALERT INFORMATION ================= */}

      <div className="card notification-info-panel">


        <h3>
          SmartChip Alert Monitoring
        </h3>


        <p className="muted">

          When the ESP32 device is connected,
          SmartChip will monitor the drying
          system for important events.

        </p>


        <div className="notification-monitor-grid">


          <MonitorItem

            title="Temperature"

            description={
              device.online
                ? "Monitoring sensor temperature"
                : "Waiting for device"
            }

            active={device.online}

          />


          <MonitorItem

            title="Humidity"

            description={
              device.online
                ? "Monitoring chamber humidity"
                : "Waiting for device"
            }

            active={device.online}

          />


          <MonitorItem

            title="SHT31 Sensors"

            description={
              device.online
                ? "Monitoring sensor health"
                : "Waiting for device"
            }

            active={device.online}

          />


          <MonitorItem

            title="SSR System"

            description={
              device.online
                ? "Monitoring heater and fan output"
                : "Waiting for device"
            }

            active={device.online}

          />


        </div>


      </div>


    </div>

  );

}



/* =========================================
   SETTINGS GROUP
========================================= */

function SettingsGroup({

  title,

  children,

}) {

  return (

    <div className="settings-group">

      <h4>

        {title}

      </h4>


      {children}

    </div>

  );

}



/* =========================================
   TOGGLE COMPONENT
========================================= */

function Toggle({

  label,

  checked,

  onChange,

}) {

  return (

    <div className="toggle-row">


      <span className="toggle-label">

        {label}

      </span>


      <label className="toggle-switch">


        <input

          type="checkbox"

          checked={checked}

          onChange={onChange}

        />


        <span className="toggle-slider"></span>


      </label>


    </div>

  );

}



/* =========================================
   MONITOR ITEM
========================================= */

function MonitorItem({

  title,

  description,

  active,

}) {

  return (

    <div className="monitor-item">


      <div className="monitor-header">


        <strong>

          {title}

        </strong>


        <span
          className={
            active
              ? "monitor-active"
              : "monitor-waiting"
          }
        >

          {active
            ? "Monitoring"
            : "Waiting"}

        </span>


      </div>


      <p>

        {description}

      </p>


    </div>

  );

}